export { default as HomePage } from './homePage';
export { default as About } from './About';
export { default as Table} from './Table';
export { default as Archive} from './Archive';
export { default as Info} from './Info';
export { default as Register} from './Register';
export { default as Article} from './Article';
export { default as AddArticle} from './AddArticle';
export { default as AddDriver} from './AddDriver';
export { default as DriversList} from './DriversList';
export { default as AdminPage} from './AdminPage';
